/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIPackage;

import UIPackage.SimpanListener;
import BackendSystemPackage.VerifikasiSystem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author RH
 */
public class SlipGajiFrame extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form SlipGajiFrame
     */
    private SimpanListener simpan;
    private VerifikasiSystem verifikasiSystem;
    
    public SlipGajiFrame() {
        initComponents();
        jButton1.addActionListener(this);
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == jButton1){
            simpan.simpanOpsiVerifikasi(1);
        }
    }

    public void setVerifikasiSystem(VerifikasiSystem verifikasiSystem) {
        this.verifikasiSystem = verifikasiSystem;
    }
    
    public void setSlipGaji(){
        int bulan = verifikasiSystem.getBulan();
        int potonganPajak = (int) (verifikasiSystem.getPajak() * verifikasiSystem.getGaji());
        jLabel2.setText("Nama: "+verifikasiSystem.getNama());
        switch (bulan){
            case 1 -> jLabel3.setText("Tanggal: Januari, tahun "+verifikasiSystem.getTahun());
            case 2 -> jLabel3.setText("Tanggal: Februari, tahun "+verifikasiSystem.getTahun());
            case 3 -> jLabel3.setText("Tanggal: Maret, tahun "+verifikasiSystem.getTahun());
            case 4 -> jLabel3.setText("Tanggal: April, tahun "+verifikasiSystem.getTahun());
            case 5 -> jLabel3.setText("Tanggal: Mei, tahun "+verifikasiSystem.getTahun());
            case 6 -> jLabel3.setText("Tanggal: Juni, tahun "+verifikasiSystem.getTahun());
            case 7 -> jLabel3.setText("Tanggal: Juli, tahun "+verifikasiSystem.getTahun());
            case 8 -> jLabel3.setText("Tanggal: Agustus, tahun "+verifikasiSystem.getTahun());
            case 9 -> jLabel3.setText("Tanggal: September, tahun "+verifikasiSystem.getTahun());
            case 10 -> jLabel3.setText("Tanggal: Oktober, tahun "+verifikasiSystem.getTahun());
            case 11 -> jLabel3.setText("Tanggal: November, tahun "+verifikasiSystem.getTahun());
            case 12 -> jLabel3.setText("Tanggal: Desember, tahun "+verifikasiSystem.getTahun());
        }
        jLabel4.setText("Gaji: "+String.valueOf(verifikasiSystem.getGaji()));
        jLabel5.setText("Potongan pajak: "+String.valueOf(potonganPajak));
    }
    
    public void setSlipLembur(){
        int bulan = verifikasiSystem.getBulan();;
        jLabel2.setText("Nama: "+verifikasiSystem.getNama());
        switch (bulan){
            case 1 -> jLabel3.setText("Tanggal: "+verifikasiSystem.getHari()+" Januari, tahun "+verifikasiSystem.getTahun());
            case 2 -> jLabel3.setText("Tanggal: "+verifikasiSystem.getHari()+" Februari, tahun "+verifikasiSystem.getTahun());
            case 3 -> jLabel3.setText("Tanggal: "+verifikasiSystem.getHari()+" Maret, tahun "+verifikasiSystem.getTahun());
            case 4 -> jLabel3.setText("Tanggal: "+verifikasiSystem.getHari()+" April, tahun "+verifikasiSystem.getTahun());
            case 5 -> jLabel3.setText("Tanggal: "+verifikasiSystem.getHari()+" Mei, tahun "+verifikasiSystem.getTahun());
            case 6 -> jLabel3.setText("Tanggal: "+verifikasiSystem.getHari()+" Juni, tahun "+verifikasiSystem.getTahun());
            case 7 -> jLabel3.setText("Tanggal: "+verifikasiSystem.getHari()+" Juli, tahun "+verifikasiSystem.getTahun());
            case 8 -> jLabel3.setText("Tanggal: "+verifikasiSystem.getHari()+" Agustus, tahun "+verifikasiSystem.getTahun());
            case 9 -> jLabel3.setText("Tanggal: "+verifikasiSystem.getHari()+" September, tahun "+verifikasiSystem.getTahun());
            case 10 -> jLabel3.setText("Tanggal: "+verifikasiSystem.getHari()+" Oktober, tahun "+verifikasiSystem.getTahun());
            case 11 -> jLabel3.setText("Tanggal: "+verifikasiSystem.getHari()+" November, tahun "+verifikasiSystem.getTahun());
            case 12 -> jLabel3.setText("Tanggal: "+verifikasiSystem.getHari()+" Desember, tahun "+verifikasiSystem.getTahun());
        }
        jLabel4.setText("Upah Lembur: "+String.valueOf(verifikasiSystem.getLembur()));
        jLabel5.setText("Potongan pajak: "+String.valueOf(verifikasiSystem.getPajak()));
    }
    
    public void addSimpanListener(SimpanListener simpan){
        this.simpan = simpan;
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SLIP GAJI KARYAWAN");

        jButton1.setText("Close");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jButton1)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlipGajiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlipGajiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlipGajiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlipGajiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlipGajiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    
}
